# Setup
title:               David Robert Quinn
tagline:             'My Life'
description:         'The life and musings of Quincy'
url:                 https://davidrobertquinn.com
baseurl:        
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              David Quinn
  url:               davidrobertquinn.com
  email:             davidrobertquinn@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
